# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Circle": "00_example.ipynb"}

modules = ["core.py"]

doc_url = "https://pages.github.optum.com./demo-nbdev/demo/"

git_url = "https://github.optum.com/demo-nbdev/demo/tree/master/"

def custom_doc_links(name): return None
