# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Circle": "00_example.ipynb"}

modules = ["core.py"]

doc_url = "https://github.optum.com/pages/yreddy31/demo-nbdev//"

git_url = "https://github.optum.com/yreddy31/demo-nbdev/tree/master/"

def custom_doc_links(name): return None
