# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_example.ipynb (unless otherwise specified).

__all__ = ['Circle']

# Cell
import math
class Circle:
    def __init__(self, r:float): self.r = r
    @property
    def perimeter(self):
        """return the perimeter of the circle"""
        return 2 * math.pi * self.r
    @property
    def area(self):
        """return the area of the circle:"""
        return math.pi * (self.r)**2